---
title: Underflow
---
flowchart
Start[Start: Key Removed] --> A{Is node leaf?}
A -- Yes --> B{Is node underflowed}
A -- No --> C[Take from left child] --> D{Does child underflow?}
D -- Yes --> Underflow
D -- No --> End
B -- No --> E{Is child leaf?}
E -- Yes --> End
E -- No --> Start
B -- Yes --> Underflow

End[End]
Underflow[Underflow Process]