---
title: Removal
---
flowchart
    Start --> SearchKey
    SearchKey -->|Found| RemoveKey[Remove Key]
    SearchKey -->|Not Found| End

    RemoveKey -->|Key in Leaf Node| RemoveKeyLeaf
    RemoveKey -->|Key in Internal Node| ReplaceFromCenterOfChildren
    RemoveKey -->|Key in Root Node| RemoveKeyRoot

    ReplaceFromCenterOfChildren --> |ChildUnderflow| HandleUnderflow --> End
    ReplaceFromCenterOfChildren -->|No Underflow| End

    RemoveKeyRoot -->|No| ReplaceFromCenterOfChildren
    RemoveKeyRoot -->|Yes| End

    HandleUnderflow[Handle Underflow]

    RemoveKeyLeaf -->|No Underflow| End
    RemoveKeyLeaf -->|Underflow| HandleUnderflow
    

    Start(Start)
    SearchKey{Search Key in B-Tree}
    RemoveKey[Remove Key]
    RemoveKeyLeaf[Remove Key from Leaf Node]
    RemoveKeyRoot{Is Root Leaf?}
    ReplaceFromCenterOfChildren[ReplaceFromCenterOfChildren]
    End{End}